name: mp3
description: A pure dart implementation of mp3 encoder and decoders.
version: 0.0.1
repository: https://github.com/xclud/dart_mp3

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
